/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Answers', [
      {
        answer_text: 'Мохито',
        question_id: 1,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Апероль',
        question_id: 1,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Маргарита',
        question_id: 1,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Это определяет форму бокала для коктейля',
        question_id: 2,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Это влияет на внешний вид напитка',
        question_id: 2,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Это особый шпионский сигнал',
        question_id: 2,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Физзы',
        question_id: 3,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Коллинзы',
        question_id: 3,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Сауэры',
        question_id: 3,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Франция',
        question_id: 4,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Испания',
        question_id: 4,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Италия',
        question_id: 4,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Его готовит чемпион мирового конкурса барменов',
        question_id: 5,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'В нем плавает настоящий бриллиант',
        question_id: 5,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'В стоимость входит хрустальный бокал для коктейля',
        question_id: 5,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Сахарные',
        question_id: 6,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Шелковые',
        question_id: 6,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Сочные',
        question_id: 6,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Бархатные',
        question_id: 6,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Невыносимая тяжесть огромного таланта',
        question_id: 7,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Рэнфилд',
        question_id: 7,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Книга Боббы Фета',
        question_id: 7,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Кокаиновый барон',
        question_id: 7,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Мачо-хата-мучо-каса',
        question_id: 8,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Мачо-дача-хата-хаус',
        question_id: 8,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Бейби-мами-хата-хаус',
        question_id: 8,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Мачо-хаус-дача-хата',
        question_id: 8,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Ride it',
        question_id: 9,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Hay Lof',
        question_id: 9,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Wicked Game',
        question_id: 9,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Thrift Shop',
        question_id: 9,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Рок',
        question_id: 10,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Блюз',
        question_id: 10,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Реп',
        question_id: 10,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Попса',
        question_id: 10,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Жених',
        question_id: 11,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Александр',
        question_id: 11,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Саша',
        question_id: 11,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Саня',
        question_id: 11,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '7',
        question_id: 12,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '8',
        question_id: 12,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '6',
        question_id: 12,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '10',
        question_id: 12,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Crazy Frog - Axel F',
        question_id: 13,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'INSTASAMKA, Лолита - На Титанике',
        question_id: 13,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Stromae - Formidable',
        question_id: 13,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'АК-47 - Оля Лукина',
        question_id: 13,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'promise.resolve("Learning to learn")',
        question_id: 14,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'console.log("Elbrus Bootcamp is cool!")',
        question_id: 14,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'console.log("Spasibo Marku!")',
        question_id: 14,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'В честь горы',
        question_id: 15,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'По приколу',
        question_id: 15,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'В честь микропроцессора',
        question_id: 15,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Answers', null, {});
  },
};
