/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Answers', [
      {
        answer_text: 'Фечить',
        question_id: 1,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Отправлять запросы на сервер',
        question_id: 1,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Писать стихи',
        question_id: 1,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Солнышко',
        question_id: 2,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'логу регу',
        question_id: 2,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '4 года опыта',
        question_id: 2,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'лОжить',
        question_id: 3,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'ложИть',
        question_id: 3,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'класть',
        question_id: 3,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Будильник',
        question_id: 4,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Сеттаймаут',
        question_id: 4,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Сетинтервал',
        question_id: 4,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Поймай меня, если сможешь',
        question_id: 5,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '42',
        question_id: 6,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: '52',
        question_id: 6,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Undefined',
        question_id: 6,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Нет такой страны',
        question_id: 7,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Зимбабве',
        question_id: 7,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Республика Чад',
        question_id: 7,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Elborus Bootcamp',
        question_id: 8,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Elburz Bootcamp',
        question_id: 8,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Также как и сейчас',
        question_id: 8,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Республика Башкортостан',
        question_id: 9,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Недалеко от белой реки',
        question_id: 9,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Не знаю правильный ответ, вопрос придумала Диана',
        question_id: 9,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Владимир Ленин',
        question_id: 10,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Оксимирон',
        question_id: 10,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Анна Викторовна',
        question_id: 10,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Ленинский Проспект',
        question_id: 11,
        isRight: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Тверская',
        question_id: 11,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer_text: 'Купчино',
        question_id: 11,
        isRight: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Answers', null, {});
  },
};
